name: 'Helm Chart AppVersion Bumper'
description: 'Bumping AppVersion based on input'
inputs:
  appVersion:  # id of input
    description: 'appVersion to replace in Helm Chart'
    required: true
    default: ''
outputs:
  result: # id of output
    description: 'appVersion Changed'
runs:
  using: 'node16'
  main: 'dist/index.js'